'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AplicacionPago
    Public Property idPagoFactura As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property MontoTotalPagado As Nullable(Of Decimal)
    Public Property Memo As String
    Public Property Fecha As Nullable(Of Date)
    Public Property idUsuario As Nullable(Of Integer)
    Public Property idMetodoPago As Nullable(Of Integer)
    Public Property idCustomer As Nullable(Of Integer)
    Public Property idCatalogoBanco As Nullable(Of Integer)
    Public Property Num_CuentaBancaria As Nullable(Of Decimal)
    Public Property idUbicacion As Nullable(Of Integer)

    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property DetalleAplicacionPago As ICollection(Of DetalleAplicacionPago) = New HashSet(Of DetalleAplicacionPago)
    Public Overridable Property Catalogo_MetodosPago As Catalogo_MetodosPago
    Public Overridable Property Catalogo_Bancos As Catalogo_Bancos
    Public Overridable Property Customers As Customers
    Public Overridable Property Ubicaciones As Ubicaciones

End Class
