'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Catalogo_NivelesPrecio
    Public Property idCategoriaPrecio As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property Descripcion As String

    Public Overridable Property NivelesPrecioProducto As ICollection(Of NivelesPrecioProducto) = New HashSet(Of NivelesPrecioProducto)
    Public Overridable Property Customers As ICollection(Of Customers) = New HashSet(Of Customers)

End Class
