'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Catalogo_MetodoPagoSAT
    Public Property idMetodoPagoSAT As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property Descripcion As String

    Public Overridable Property SalesOrder As ICollection(Of SalesOrder) = New HashSet(Of SalesOrder)
    Public Overridable Property Resp_SalesOrder As ICollection(Of Resp_SalesOrder) = New HashSet(Of Resp_SalesOrder)
    Public Overridable Property Invoice_SO As ICollection(Of Invoice_SO) = New HashSet(Of Invoice_SO)

End Class
