'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Catalogo_Productos
    Public Property idProducto As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property Descripcion As String
    Public Property Categoria As String
    Public Property Precio As Nullable(Of Decimal)

    Public Overridable Property StockDisponible As ICollection(Of StockDisponible) = New HashSet(Of StockDisponible)
    Public Overridable Property DetalleSalesOrder As ICollection(Of DetalleSalesOrder) = New HashSet(Of DetalleSalesOrder)
    Public Overridable Property NivelesPrecioProducto As ICollection(Of NivelesPrecioProducto) = New HashSet(Of NivelesPrecioProducto)
    Public Overridable Property Resp_DetalleSalesOrder As ICollection(Of Resp_DetalleSalesOrder) = New HashSet(Of Resp_DetalleSalesOrder)
    Public Overridable Property DescuentoClienteArticulo As ICollection(Of DescuentoClienteArticulo) = New HashSet(Of DescuentoClienteArticulo)

End Class
