'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfiguracionCorreo
    Public Property idCorreo As Integer
    Public Property DireccionCorreo As String
    Public Property NombreCuenta As String
    Public Property PasswordCuenta As String
    Public Property Protocolo As String
    Public Property Puerto As Nullable(Of Integer)
    Public Property SSL As Boolean
    Public Property ServidorEntrante As String
    Public Property ServidorSaliente As String

End Class
