'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customers
    Public Property idCustomer As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property Nombre As String
    Public Property idCategoriaPrecio As Nullable(Of Integer)
    Public Property idCatalogoTipoCliente As Nullable(Of Integer)
    Public Property RFC As String
    Public Property Limite_Credito As Nullable(Of Decimal)
    Public Property Dias_Atraso As Nullable(Of Decimal)
    Public Property idCatalogoTerminos As Nullable(Of Integer)

    Public Overridable Property AplicacionPago As ICollection(Of AplicacionPago) = New HashSet(Of AplicacionPago)
    Public Overridable Property Catalogo_NivelesPrecio As Catalogo_NivelesPrecio
    Public Overridable Property Catalogo_Terminos As Catalogo_Terminos
    Public Overridable Property Catalogo_TipoCliente As Catalogo_TipoCliente
    Public Overridable Property Invoice_SO As ICollection(Of Invoice_SO) = New HashSet(Of Invoice_SO)
    Public Overridable Property SalesOrder As ICollection(Of SalesOrder) = New HashSet(Of SalesOrder)
    Public Overridable Property Resp_SalesOrder As ICollection(Of Resp_SalesOrder) = New HashSet(Of Resp_SalesOrder)
    Public Overridable Property DescuentoClienteArticulo As ICollection(Of DescuentoClienteArticulo) = New HashSet(Of DescuentoClienteArticulo)

End Class
