'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleAplicacionPago
    Public Property idDetalleMontoPagado As Integer
    Public Property idPagoFactura As Nullable(Of Integer)
    Public Property Ref_Pago As String
    Public Property ImporteOriginal As Nullable(Of Decimal)
    Public Property ImportePagar As Nullable(Of Decimal)
    Public Property PagoRealizado As Decimal
    Public Property Moneda As String
    Public Property idInvoice As Nullable(Of Integer)

    Public Overridable Property AplicacionPago As AplicacionPago
    Public Overridable Property Invoice_SO As Invoice_SO

End Class
