'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estatus
    Public Property idEstatus As Integer
    Public Property idConcepto As Integer
    Public Property ClaveInterna As String
    Public Property ClaveExterna As String
    Public Property Descripcion As String

    Public Overridable Property Conceptos As Conceptos
    Public Overridable Property SalesOrder As ICollection(Of SalesOrder) = New HashSet(Of SalesOrder)
    Public Overridable Property Invoice_SO As ICollection(Of Invoice_SO) = New HashSet(Of Invoice_SO)
    Public Overridable Property DetalleSalesOrder As ICollection(Of DetalleSalesOrder) = New HashSet(Of DetalleSalesOrder)
    Public Overridable Property Resp_DetalleSalesOrder As ICollection(Of Resp_DetalleSalesOrder) = New HashSet(Of Resp_DetalleSalesOrder)
    Public Overridable Property Resp_SalesOrder As ICollection(Of Resp_SalesOrder) = New HashSet(Of Resp_SalesOrder)

End Class
