'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estimaciones
    Public Property idEstimacion As Integer
    Public Property idCustomer As Nullable(Of Integer)
    Public Property idUbicacion As Nullable(Of Integer)
    Public Property Nota As String
    Public Property idEstatus As Nullable(Of Integer)
    Public Property FormaPago As String
    Public Property MetodoDePago As String
    Public Property UsoCFDI As String
    Public Property FechaCreacion As Nullable(Of Date)
    Public Property idUsuario As Nullable(Of Integer)
    Public Property SubTotal As Nullable(Of Decimal)
    Public Property Descuento As Nullable(Of Decimal)
    Public Property TotalImpuestos As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property idMetodoPagoSAT As Nullable(Of Integer)
    Public Property idUsoCFDI As Nullable(Of Integer)
    Public Property idFormaPago As Nullable(Of Integer)

End Class
