'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Invoice_SO
    Public Property idInvoice As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property idSalesOrder As Nullable(Of Integer)
    Public Property idEstatus As Nullable(Of Integer)
    Public Property FechaCreacion As Nullable(Of Date)
    Public Property Subtotal As Nullable(Of Decimal)
    Public Property Total_Impuestos As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property ImporteAdeudado As Nullable(Of Decimal)
    Public Property idCustomer As Nullable(Of Integer)
    Public Property idUsuario As Nullable(Of Integer)
    Public Property UUID As String
    Public Property NS_XML As Nullable(Of Integer)
    Public Property NS_PDF As Nullable(Of Integer)
    Public Property idUbicacion As Nullable(Of Integer)
    Public Property idMetodoPagoSAT As Nullable(Of Integer)

    Public Overridable Property Estatus As Estatus
    Public Overridable Property SalesOrder As SalesOrder
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property DetalleAplicacionPago As ICollection(Of DetalleAplicacionPago) = New HashSet(Of DetalleAplicacionPago)
    Public Overridable Property Customers As Customers
    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Catalogo_MetodoPagoSAT As Catalogo_MetodoPagoSAT

End Class
