'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LogCancelaciones
    Public Property idLogCancelaciones As Integer
    Public Property MotivoCancelacion As String
    Public Property FolioSalesOrder As String
    Public Property Usuario As String

End Class
