'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NivelesPrecioProducto
    Public Property idNivelPrecioProducto As Integer
    Public Property idProducto As Nullable(Of Integer)
    Public Property idCategoriaPrecio As Nullable(Of Integer)
    Public Property Precio As Nullable(Of Decimal)

    Public Overridable Property Catalogo_NivelesPrecio As Catalogo_NivelesPrecio
    Public Overridable Property Catalogo_Productos As Catalogo_Productos

End Class
