'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class PVO_NetsuiteEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PVO_NetsuiteEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Catalogo_Idiomas() As DbSet(Of Catalogo_Idiomas)
    Public Overridable Property ConfiguracionCorreo() As DbSet(Of ConfiguracionCorreo)
    Public Overridable Property Parametros() As DbSet(Of Parametros)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)
    Public Overridable Property webpages_Acciones() As DbSet(Of webpages_Acciones)
    Public Overridable Property webpages_Membership() As DbSet(Of webpages_Membership)
    Public Overridable Property webpages_OAuthMembership() As DbSet(Of webpages_OAuthMembership)
    Public Overridable Property webpages_Roles() As DbSet(Of webpages_Roles)
    Public Overridable Property UsuarioUbicaciones() As DbSet(Of UsuarioUbicaciones)
    Public Overridable Property SalesOrder() As DbSet(Of SalesOrder)
    Public Overridable Property StockDisponible() As DbSet(Of StockDisponible)
    Public Overridable Property Ubicaciones() As DbSet(Of Ubicaciones)
    Public Overridable Property Catalogo_Productos() As DbSet(Of Catalogo_Productos)
    Public Overridable Property Conceptos() As DbSet(Of Conceptos)
    Public Overridable Property Estatus() As DbSet(Of Estatus)
    Public Overridable Property Invoice_SO() As DbSet(Of Invoice_SO)
    Public Overridable Property AplicacionPago() As DbSet(Of AplicacionPago)
    Public Overridable Property DetalleAplicacionPago() As DbSet(Of DetalleAplicacionPago)
    Public Overridable Property Catalogo_MetodosPago() As DbSet(Of Catalogo_MetodosPago)
    Public Overridable Property Catalogo_MetodoPagoSAT() As DbSet(Of Catalogo_MetodoPagoSAT)
    Public Overridable Property DetalleSalesOrder() As DbSet(Of DetalleSalesOrder)
    Public Overridable Property Catalogo_FormasPagoSAT() As DbSet(Of Catalogo_FormasPagoSAT)
    Public Overridable Property Catalogo_UsoCFDI() As DbSet(Of Catalogo_UsoCFDI)
    Public Overridable Property Catalogo_NivelesPrecio() As DbSet(Of Catalogo_NivelesPrecio)
    Public Overridable Property NivelesPrecioProducto() As DbSet(Of NivelesPrecioProducto)
    Public Overridable Property Catalogo_TipoCliente() As DbSet(Of Catalogo_TipoCliente)
    Public Overridable Property Resp_DetalleSalesOrder() As DbSet(Of Resp_DetalleSalesOrder)
    Public Overridable Property Resp_SalesOrder() As DbSet(Of Resp_SalesOrder)
    Public Overridable Property Catalogo_Bancos() As DbSet(Of Catalogo_Bancos)
    Public Overridable Property Catalogo_Exportaciones() As DbSet(Of Catalogo_Exportaciones)
    Public Overridable Property DescuentoClienteArticulo() As DbSet(Of DescuentoClienteArticulo)
    Public Overridable Property Catalogo_Terminos() As DbSet(Of Catalogo_Terminos)
    Public Overridable Property Customers() As DbSet(Of Customers)
    Public Overridable Property Catalogo_Cuentas() As DbSet(Of Catalogo_Cuentas)
    Public Overridable Property Catalogo_Terminales() As DbSet(Of Catalogo_Terminales)
    Public Overridable Property Catalogo_CuentasBancarias() As DbSet(Of Catalogo_CuentasBancarias)
    Public Overridable Property LogCancelaciones() As DbSet(Of LogCancelaciones)
    Public Overridable Property RecepcionMercancia() As DbSet(Of RecepcionMercancia)
    Public Overridable Property Catalogo_Colonias() As DbSet(Of Catalogo_Colonias)
    Public Overridable Property Catalogo_Cp() As DbSet(Of Catalogo_Cp)
    Public Overridable Property Catalogo_Estados() As DbSet(Of Catalogo_Estados)
    Public Overridable Property Catalogo_Localidades() As DbSet(Of Catalogo_Localidades)
    Public Overridable Property Catalogo_Mostrador() As DbSet(Of Catalogo_Mostrador)
    Public Overridable Property Catalogo_Municipios() As DbSet(Of Catalogo_Municipios)
    Public Overridable Property Catalogo_Paises() As DbSet(Of Catalogo_Paises)
    Public Overridable Property Catalogo_RegimenFiscal() As DbSet(Of Catalogo_RegimenFiscal)
    Public Overridable Property LogSalesOrder() As DbSet(Of LogSalesOrder)
    Public Overridable Property Estimaciones() As DbSet(Of Estimaciones)
    Public Overridable Property Negadas() As DbSet(Of Negadas)

    Public Overridable Function JG_ConsultarPlantillaMRP(numPlanta As String, numMostrador As String) As ObjectResult(Of JG_ConsultarPlantillaMRP_Result)
        Dim numPlantaParameter As ObjectParameter = If(numPlanta IsNot Nothing, New ObjectParameter("NumPlanta", numPlanta), New ObjectParameter("NumPlanta", GetType(String)))

        Dim numMostradorParameter As ObjectParameter = If(numMostrador IsNot Nothing, New ObjectParameter("NumMostrador", numMostrador), New ObjectParameter("NumMostrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of JG_ConsultarPlantillaMRP_Result)("JG_ConsultarPlantillaMRP", numPlantaParameter, numMostradorParameter)
    End Function

    Public Overridable Function JG_ConsultarPrecioStock(numPlanta As String, numMostrador As String, numPrecioBase As String) As ObjectResult(Of JG_ConsultarPrecioStock_Result)
        Dim numPlantaParameter As ObjectParameter = If(numPlanta IsNot Nothing, New ObjectParameter("NumPlanta", numPlanta), New ObjectParameter("NumPlanta", GetType(String)))

        Dim numMostradorParameter As ObjectParameter = If(numMostrador IsNot Nothing, New ObjectParameter("NumMostrador", numMostrador), New ObjectParameter("NumMostrador", GetType(String)))

        Dim numPrecioBaseParameter As ObjectParameter = If(numPrecioBase IsNot Nothing, New ObjectParameter("NumPrecioBase", numPrecioBase), New ObjectParameter("NumPrecioBase", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of JG_ConsultarPrecioStock_Result)("JG_ConsultarPrecioStock", numPlantaParameter, numMostradorParameter, numPrecioBaseParameter)
    End Function

    Public Overridable Function JG_ConsultarProductoCoincidencia(coincidencia As String) As ObjectResult(Of JG_ConsultarProductoCoincidencia_Result)
        Dim coincidenciaParameter As ObjectParameter = If(coincidencia IsNot Nothing, New ObjectParameter("Coincidencia", coincidencia), New ObjectParameter("Coincidencia", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of JG_ConsultarProductoCoincidencia_Result)("JG_ConsultarProductoCoincidencia", coincidenciaParameter)
    End Function

    Public Overridable Function JG_ConsultarProductoCoincidenciaClaveProd(coincidencia As String) As ObjectResult(Of JG_ConsultarProductoCoincidenciaClaveProd_Result)
        Dim coincidenciaParameter As ObjectParameter = If(coincidencia IsNot Nothing, New ObjectParameter("Coincidencia", coincidencia), New ObjectParameter("Coincidencia", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of JG_ConsultarProductoCoincidenciaClaveProd_Result)("JG_ConsultarProductoCoincidenciaClaveProd", coincidenciaParameter)
    End Function

    Public Overridable Function JG_CoincidenciaMetodoPago(coincidencia As String) As ObjectResult(Of Nullable(Of Integer))
        Dim coincidenciaParameter As ObjectParameter = If(coincidencia IsNot Nothing, New ObjectParameter("Coincidencia", coincidencia), New ObjectParameter("Coincidencia", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("JG_CoincidenciaMetodoPago", coincidenciaParameter)
    End Function

End Class
