'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecepcionMercancia
    Public Property idRecepcionArticulos As Integer
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property idEstatus As Nullable(Of Integer)
    Public Property UbicacionDestino As Nullable(Of Integer)
    Public Property FechaRecepcion As Nullable(Of Date)
    Public Property idUsuario As Nullable(Of Integer)
    Public Property Nota As String

    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Usuarios As Usuarios

End Class
