'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Resp_SalesOrder
    Public Property idRespSalesOrder As Integer
    Public Property idCustomer As Nullable(Of Integer)
    Public Property idUbicacion As Nullable(Of Integer)
    Public Property Nota As String
    Public Property idEstatus As Nullable(Of Integer)
    Public Property FormaPago As String
    Public Property MetodoDePago As String
    Public Property UsoCFDI As String
    Public Property FechaCreacion As Nullable(Of Date)
    Public Property idUsuario As Nullable(Of Integer)
    Public Property idMetodoPagoSAT As Nullable(Of Integer)
    Public Property idUsoCFDI As Nullable(Of Integer)
    Public Property idFormaPago As Nullable(Of Integer)

    Public Overridable Property Catalogo_FormasPagoSAT As Catalogo_FormasPagoSAT
    Public Overridable Property Catalogo_MetodoPagoSAT As Catalogo_MetodoPagoSAT
    Public Overridable Property Catalogo_UsoCFDI As Catalogo_UsoCFDI
    Public Overridable Property Estatus As Estatus
    Public Overridable Property Resp_DetalleSalesOrder As ICollection(Of Resp_DetalleSalesOrder) = New HashSet(Of Resp_DetalleSalesOrder)
    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property Customers As Customers

End Class
