'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalesOrder
    Public Property idSalesOrder As Integer
    Public Property idCustomer As Nullable(Of Integer)
    Public Property idUbicacion As Nullable(Of Integer)
    Public Property Nota As String
    Public Property FormaPago As String
    Public Property MetodoDePago As String
    Public Property UsoCFDI As String
    Public Property FechaCreacion As Nullable(Of Date)
    Public Property idUsuario As Nullable(Of Integer)
    Public Property SubTotal As Nullable(Of Decimal)
    Public Property Descuento As Nullable(Of Decimal)
    Public Property TotalImpuestos As Nullable(Of Decimal)
    Public Property VAT_MX As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property NS_ExternalID As String
    Public Property idEstatus As Nullable(Of Integer)
    Public Property idMetodoPagoSAT As Nullable(Of Integer)
    Public Property idUsoCFDI As Nullable(Of Integer)
    Public Property idFormaPago As Nullable(Of Integer)
    Public Property EsCartaPorte As Nullable(Of Boolean)

    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property Estatus As Estatus
    Public Overridable Property Invoice_SO As ICollection(Of Invoice_SO) = New HashSet(Of Invoice_SO)
    Public Overridable Property Catalogo_MetodoPagoSAT As Catalogo_MetodoPagoSAT
    Public Overridable Property DetalleSalesOrder As ICollection(Of DetalleSalesOrder) = New HashSet(Of DetalleSalesOrder)
    Public Overridable Property Catalogo_FormasPagoSAT As Catalogo_FormasPagoSAT
    Public Overridable Property Catalogo_UsoCFDI As Catalogo_UsoCFDI
    Public Overridable Property Customers As Customers

End Class
