'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StockDisponible
    Public Property DetalleInventarioDisponible As Integer
    Public Property idProducto As Nullable(Of Integer)
    Public Property idUbicacion As Nullable(Of Integer)
    Public Property StockDisponible1 As Nullable(Of Decimal)
    Public Property NumLote As String
    Public Property IssueInventory As String

    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Catalogo_Productos As Catalogo_Productos

End Class
