'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ubicaciones
    Public Property idUbicacion As Integer
    Public Property DescripcionAlmacen As String
    Public Property NS_InternalID As Nullable(Of Integer)
    Public Property EsAlmacen As Nullable(Of Boolean)

    Public Overridable Property SalesOrder As ICollection(Of SalesOrder) = New HashSet(Of SalesOrder)
    Public Overridable Property StockDisponible As ICollection(Of StockDisponible) = New HashSet(Of StockDisponible)
    Public Overridable Property UsuarioUbicaciones As ICollection(Of UsuarioUbicaciones) = New HashSet(Of UsuarioUbicaciones)
    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)
    Public Overridable Property Resp_SalesOrder As ICollection(Of Resp_SalesOrder) = New HashSet(Of Resp_SalesOrder)
    Public Overridable Property Catalogo_Terminales As ICollection(Of Catalogo_Terminales) = New HashSet(Of Catalogo_Terminales)
    Public Overridable Property AplicacionPago As ICollection(Of AplicacionPago) = New HashSet(Of AplicacionPago)
    Public Overridable Property Invoice_SO As ICollection(Of Invoice_SO) = New HashSet(Of Invoice_SO)
    Public Overridable Property RecepcionMercancia As ICollection(Of RecepcionMercancia) = New HashSet(Of RecepcionMercancia)

End Class
