'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property idUsuario As Integer
    Public Property Nombre As String
    Public Property Correo As String
    Public Property InformacionContacto As String
    Public Property CuentaActiva As Boolean
    Public Property FechaModificacion As Date
    Public Property InfoCambios As String
    Public Property Lenguaje As String
    Public Property MostradorPref As Nullable(Of Integer)

    Public Overridable Property Parametros As ICollection(Of Parametros) = New HashSet(Of Parametros)
    Public Overridable Property webpages_Roles As ICollection(Of webpages_Roles) = New HashSet(Of webpages_Roles)
    Public Overridable Property UsuarioUbicaciones As ICollection(Of UsuarioUbicaciones) = New HashSet(Of UsuarioUbicaciones)
    Public Overridable Property SalesOrder As ICollection(Of SalesOrder) = New HashSet(Of SalesOrder)
    Public Overridable Property Invoice_SO As ICollection(Of Invoice_SO) = New HashSet(Of Invoice_SO)
    Public Overridable Property AplicacionPago As ICollection(Of AplicacionPago) = New HashSet(Of AplicacionPago)
    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Resp_SalesOrder As ICollection(Of Resp_SalesOrder) = New HashSet(Of Resp_SalesOrder)
    Public Overridable Property RecepcionMercancia As ICollection(Of RecepcionMercancia) = New HashSet(Of RecepcionMercancia)

End Class
